### ISSUE TITLE
Error extending a sheet by editor, non-owner

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#25]
@jaspervanderklis was making commit https://github.com/scarlatti/argos-essercizi/commit/c02ca41c60eae4b104c046d1d82c722d28c71614, to add new sonatas to a volunteer's workload an then calling `extend_sheet` to extend the sheets.

However, this caused an error that interrupted the extension of the sheet halfway through.

Compared to previous times this operation has been completed: Previously, I always ran this operation, and I think I am the creator/owner of the sheets. @jaspervanderklis has been recently added as editor, using the properties of the template configuration file, see [here](https://github.com/scarlatti/argos-essercizi/blob/c02ca41c60eae4b104c046d1d82c722d28c71614/input/template_definitions.json#L18-L22).

The error is:
```json
{
  "code": 400,
  "message": "Invalid requests[40].addProtectedRange: You can't remove yourself as an editor",
  "status": "INVALID ARGUMENT"
}
```

I am wondering what I should do immediately. The best course of action seems to be: (a) delete partial sheet, (b) rerun as owner. But I am wondering if that will make it harder to investigate the bug—@josephlou5 let me know!

![Terminal output of the error](https://github.com/scarlatti/roseingrave/assets/11770469/39066844-a56a-436f-9c1d-902e72c37b3b)

![Incomplete state of the spreadsheet](https://github.com/scarlatti/roseingrave/assets/11770469/a5f2587f-d357-47dd-b30e-4d6d481913de)

**Comment by josephlou5** [comment]
Resolved with commit 2fb5731aab4df76bd78a6b6f2a136a5c6defa79a: all editors of the spreadsheet (except for the volunteer) are now added to the protected range.

**Comment by jaspervanderklis** [comment]
Issue described above still persists for me with new Roseingrave version (exact same error). Thanks in advance!
